### PR TITLE
Remove deprecated st2actions import

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by nullkarma** [comment]
@LindsayHill may I have an invite for colab? ty

**Comment by LindsayHill** [comment]
> Could you bump the major version, please? Looks like a breaking change.

Change should not be breaking (assuming user has ST2 >= 1.6). But I too would like to see version bump, so release machinery creates new GH tag.

**Comment by enykeev** [comment]
Yeah, I'll do that on the weekend. Figured it out too late and don't want to upset CI too much on a work day.

**Comment by enykeev** [comment]
@nullkarma I've bumped patch version as it's not a breaking change

**Pull request merged**
